### ISSUE TITLE
Custom Folder for User Certificates

### ISSUE THREAD

**Issue by nullasync** [lupohan44/TrustUserCertificates#1]
Hi, i tried installing certificate using custom folder method but not working after few reboots. Need to add certs manually then it will shown as system certificate.

**Comment by lupohan44** [comment]
What do you mean not working after few reboots?

**Comment by nullasync** [comment]
4. (Optional) create a file named /data/adb/trustusercerts/no_user_cert and put certificates into /data/adb/trustusercerts/certificates - This step will make module using certificates from this folder instead of user certificates

I followed these step as above, but it won't installs as system certs.

**Comment by lupohan44** [comment]
May I know the naming of your certificates in /data/adb/trustusercerts/certificates?

**Comment by nullasync** [comment]
> May I know the naming of your certificates in /data/adb/trustusercerts/certificates?

Sure. Please see attached photo. Thanks. I don't know if i'm doing it the right way, but it doesn't shows up in system certs. 
![IMG_20240220_230002](https://github.com/lupohan44/TrustUserCertificates/assets/74730093/fedf2573-8a3d-49cc-96d0-6a23d279e78e)

**Comment by lupohan44** [comment]
Your filename is inccorrect. Please refer to this https://medium.com/hackers-secrets/adding-a-certificate-to-android-system-trust-store-ae8ca3519a85
> openssl x509 -inform PEM -subject_hash_old -in <exported_cert_file>| head -1
> mv <exported_cert_file> <old_hash>.0

The filename should be the hash of the certificate.
There is another easy way to do this, you can install certificate as user certificate, and you should find the renamed certificate in folder `/data/misc/user/0/cacerts-added`, copy it to custom folder
